spring:
  config:
    activate:
      on-profile: dev # 환경 이름 설정
  datasource:
    url: jdbc:mysql://localhost:3306/irecipe
    username: root
    password: asdfasdf
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: none
        default_batch_fetch_size: 1000
  security:
    user:
      name: irecipe
      password: irecipe
cloud:
  aws:
    s3:
      bucket: irecipebucket
    credentials:
      access-key: AKIAZQ3DTNPO2J3M4O54
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false